// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thhojeobcilqcvuylcga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoaG9qZW9iY2lscWN2dXlsY2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTQ0ODAsImV4cCI6MjA2OTQ3MDQ4MH0.UVpPW5bngViOswIyRcq9duh1K4SX0q_dsUwcNFWM5G8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});